# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.2

branches:
   only:
   - master
   - develop

env:
   global:
   - WORKSPACE="SStickerKit.xcworkspace"
   - IOS_FRAMEWORK_SCHEME="SStickerKit"
   - iOS_DEMO_SCHEME="SStickerKitDemo-iOS"
   - macOS_DEMO_SCHEME="SStickerKitDemo-macOS"

   matrix:
   - DESTINATION="OS=11.3,name=iPhone X"        RUN_TESTS="YES" BUILD_DEMO="iOS" POD_LINT="YES" ENABLECCODECOVERAGE="YES"
   - DESTINATION="OS=10.3.1,name=iPhone 7 Plus" RUN_TESTS="YES" BUILD_DEMO="iOS" POD_LINT="NO"  ENABLECCODECOVERAGE="NO"
   - DESTINATION="OS=9.3,name=iPhone 6"         RUN_TESTS="YES" BUILD_DEMO="iOS" POD_LINT="NO"  ENABLECCODECOVERAGE="NO"
   - DESTINATION="OS=9.3,name=iPhone 6"         RUN_TESTS="YES" BUILD_DEMO="iOS" POD_LINT="NO"  ENABLECCODECOVERAGE="NO"

script:
- set -o pipefail

- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" ENABLE_TESTABILITY=YES test | xcpretty;
  else
    xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" | xcpretty;
  fi

- if [ $BUILD_DEMO == "iOS" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$iOS_DEMO_SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO build | xcpretty;
  fi

- if [ $BUILD_DEMO == "macOS" ]; then

  fi

- if [ $ENABLECCODECOVERAGE = "YES" ]; then
    xcodebuild -enableCodeCoverage YES -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO test | xcpretty;
  fi

# Run `pod lib lint` if specified
- if [ $POD_LINT == "YES" ]; then
    pod lib lint;
  fi

notifications:
   slack: cyrex-group:ByK4WXNdYYjQ1yYZ2tjDOKyr

after_success:
- if [ $ENABLECCODECOVERAGE = "YES"]; then
    bash <(curl -s https://codecov.io/bash)
  fi
